(setq site-start-directory (concat user-emacs-directory "/site-start.d/"))

(load-file (concat site-start-directory "10-repositories.el"))
(load-file (concat site-start-directory "20-editor.el"))
(load-file (concat site-start-directory "30-ansi-coloring-in-compilation-mode.el"))
(load-file (concat site-start-directory "40-recompile-elisp.el"))
(load-file (concat site-start-directory "50-delete-without-kill-ring.el"))
(load-file (concat site-start-directory "50-ace-window.el"))
(load-file (concat site-start-directory "50-company.el"))
(load-file (concat site-start-directory "50-diff-hl-mode.el"))
(load-file (concat site-start-directory "50-flycheck.el"))
(load-file (concat site-start-directory "50-kill-file-path.el"))
(load-file (concat site-start-directory "50-recentf.el"))
(load-file (concat site-start-directory "50-ttcn-mode.el"))
(load-file (concat site-start-directory "50-yasnippet.el"))
(load-file (concat site-start-directory "50-ws-butler.el"))
(load-file (concat site-start-directory "50-pin-buffer.el"))
(load-file (concat site-start-directory "50-bookmark-bmenu.el"))
(load-file (concat site-start-directory "100-bindings.el"))
